### ISSUE TITLE
`rows` on textarea are not responsive

### ISSUE THREAD

**Issue by buhman** [sudokode/pbwww#10]
The `cols` thing is actually ignored and overriden by `form-control`.

The only thing I can think of with the current layout is something like:

``` less
.paste-content {
  @media (max-width: @screen-xs-max) {
    height: some-constant
  }
  @media (min-width: @screen-sm-min) {
    height: some-other-constant
  }
}
```

…which corresponds to the current column transitions. Throwing in a `resize: vertical` might also make sense.

I'd probably add it to [pbs](https://github.com/ptpb/pbs/) because [/f](https://ptpb.pw/f) needs it too.
